### ISSUE TITLE
Does this work with QMK?

### ISSUE THREAD

**Issue by geocine** [w4ilun/pocket-keyboard#5]
First of all, thank you for sharing this wonderful work to the community. I have a few questions. Does this work with QMK firmware? Also did you use SMT service of Seeed studio?

**Comment by w4ilun** [comment]
Thanks! It should work with QMK as well, though I haven't tried it. I did the SMT soldering myself, but Seeed/JLC would've made things a lot easier :p

**Comment by geocine** [comment]
Thanks @w4ilun
