### ISSUE TITLE
How do you add a bootloader to this PCB?

### ISSUE THREAD

**Issue by geocine** [w4ilun/pocket-keyboard#6]
Does this have a bootloader like the regular Pro Micro? Or, are there some specific steps to add bootloader to be able to enter DFU?

**Comment by w4ilun** [comment]
From the factory it comes with DFU bootloader, so you can upload your firmware using DFU right away. If you would like an "Arduino" bootloader (i.e. Pro Micro - over serial), then you can use an ISP flasher to update it
